sudo: required
services:
 - docker

before_install:
 - docker build -t lsprangers/docker-mmm -f Dockerfile.dev .

script:
 - docker run -e CI=true lsprangers/docker-mmm npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-mmm"
 env: "Dockermmm-env"
 bucekt_name: "elasticbeanstalk-us-east-1-954572926261"
 bucket_path: "resources/_runtime/_embedded_extensions/docker-mmm/"
 on:
  branch: main
 access_key_id: $AWSSECRETID
 secret_access_key: "$AWSSECRETVALUE"